### ISSUE TITLE
Requirements to make it work on M1

### ISSUE THREAD

**Issue by abij** [brycedrennan/imaginAIry#7] opened 2022-09-16 09:27 UTC
While installing `pip install imaginairy` on Mac (M1) it needs a dependency `basicsr`, this will build from the source and fails: `error: can't find Rust compiler`

After installing rust on the [recommended way](https://www.rust-lang.org/tools/install) and restarting the terminal it was able to install the package.

After successfully installing there was a runtime issue:
The `protobuf` version  `3.19.5` has an [issue](https://github.com/protocolbuffers/protobuf/issues/10571). need to downgrade / pin protobuf (`pip install protobuf==3.19.4`)

Downloading,.... waiting for first image to appear… :)

**Comment by brycedrennan** [comment] 2022-09-16 14:46
Thanks for the feedback.  I'd love to know what compiled in rust. I don't have rust installed and that package is working for me 🤷‍♂️ I'm trying to reproduce that issue.

What version of python are you on?

**Comment by brycedrennan** [comment] 2022-09-16 15:27
Ive updated the package to mitigate the protobuf issue.  I've been unable to find where the rust dependency came from thouh.

**Comment by brycedrennan** [comment] 2022-09-17 15:23
I'll close this for now but let me know if you have more info.

**Comment by abrambailey** [comment] 2022-09-19 19:43
![image](https://user-images.githubusercontent.com/978462/191102030-ee280885-a17f-4a5f-87b0-91467cb8de67.png)

**Comment by abrambailey** [comment] 2022-09-19 19:45
Resolved by running `sudo pip3 install setuptools-rust` first

**Comment by abrambailey** [comment] 2022-09-19 19:46
Hit this next:

```
  Building wheel for tokenizers (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for tokenizers (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [53 lines of output]
      Error in sitecustomize; set PYTHONVERBOSE for traceback:
      AssertionError:
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-12-arm64-cpython-310
      creating build/lib.macosx-12-arm64-cpython-310/tokenizers
      copying py_src/tokenizers/__init__.py -> build/lib.macosx-12-arm64-cpython-310/tokenizers
      creating build/lib.macosx-12-arm64-cpython-310/tokenizers/models
      copying py_src/tokenizers/models/__init__.py -> build/lib.macosx-12-arm64-cpython-310/tokenizers/models
      creating build/lib.macosx-12-arm64-cpython-310/tokenizers/decoders
      copying py_src/tokenizers/decoders/__init__.py -> build/lib.macosx-12-arm64-cpython-310/tokenizers/decoders
      creating build/lib.macosx-12-arm64-cpython-310/tokenizers/normalizers
      copying py_src/tokenizers/normalizers/__init__.py -> build/lib.macosx-12-arm64-cpython-310/tokenizers/normalizers
      creating build/lib.macosx-12-arm64-cpython-310/tokenizers/pre_tokenizers
      copying py_src/tokenizers/pre_tokenizers/__init__.py -> build/lib.macosx-12-arm64-cpython-310/tokenizers/pre_tokenizers
      creating build/lib.macosx-12-arm64-cpython-310/tokenizers/processors
      copying py_src/tokenizers/processors/__init__.py -> build/lib.macosx-12-arm64-cpython-310/tokenizers/processors
      creating build/lib.macosx-12-arm64-cpython-310/tokenizers/trainers
      copying py_src/tokenizers/trainers/__init__.py -> build/lib.macosx-12-arm64-cpython-310/tokenizers/trainers
      creating build/lib.macosx-12-arm64-cpython-310/tokenizers/implementations
      copying py_src/tokenizers/implementations/byte_level_bpe.py -> build/lib.macosx-12-arm64-cpython-310/tokenizers/implementations
      copying py_src/tokenizers/implementations/sentencepiece_unigram.py -> build/lib.macosx-12-arm64-cpython-310/tokenizers/implementations
      copying py_src/tokenizers/implementations/sentencepiece_bpe.py -> build/lib.macosx-12-arm64-cpython-310/tokenizers/implementations
      copying py_src/tokenizers/implementations/base_tokenizer.py -> build/lib.macosx-12-arm64-cpython-310/tokenizers/implementations
      copying py_src/tokenizers/implementations/__init__.py -> build/lib.macosx-12-arm64-cpython-310/tokenizers/implementations
      copying py_src/tokenizers/implementations/char_level_bpe.py -> build/lib.macosx-12-arm64-cpython-310/tokenizers/implementations
      copying py_src/tokenizers/implementations/bert_wordpiece.py -> build/lib.macosx-12-arm64-cpython-310/tokenizers/implementations
      creating build/lib.macosx-12-arm64-cpython-310/tokenizers/tools
      copying py_src/tokenizers/tools/__init__.py -> build/lib.macosx-12-arm64-cpython-310/tokenizers/tools
      copying py_src/tokenizers/tools/visualizer.py -> build/lib.macosx-12-arm64-cpython-310/tokenizers/tools
      copying py_src/tokenizers/__init__.pyi -> build/lib.macosx-12-arm64-cpython-310/tokenizers
      copying py_src/tokenizers/models/__init__.pyi -> build/lib.macosx-12-arm64-cpython-310/tokenizers/models
      copying py_src/tokenizers/decoders/__init__.pyi -> build/lib.macosx-12-arm64-cpython-310/tokenizers/decoders
      copying py_src/tokenizers/normalizers/__init__.pyi -> build/lib.macosx-12-arm64-cpython-310/tokenizers/normalizers
      copying py_src/tokenizers/pre_tokenizers/__init__.pyi -> build/lib.macosx-12-arm64-cpython-310/tokenizers/pre_tokenizers
      copying py_src/tokenizers/processors/__init__.pyi -> build/lib.macosx-12-arm64-cpython-310/tokenizers/processors
      copying py_src/tokenizers/trainers/__init__.pyi -> build/lib.macosx-12-arm64-cpython-310/tokenizers/trainers
      copying py_src/tokenizers/tools/visualizer-styles.css -> build/lib.macosx-12-arm64-cpython-310/tokenizers/tools
      running build_ext
      running build_rust
      error: can't find Rust compiler

      If you are using an outdated pip version, it is possible a prebuilt wheel is available for this package but pip is not able to install from it. Installing from the wheel would avoid the need for a Rust compiler.

      To update pip, run:

          pip install --upgrade pip

      and then retry package installation.

      If you did intend to build this package from source, try installing a Rust compiler from your system package manager and ensure it is on the PATH during installation. Alternatively, rustup (available at https://rustup.rs) is the recommended way to download and update the Rust compiler toolchain.
      [end of output]
```

**Comment by abrambailey** [comment] 2022-09-19 19:59
Managed to get it working after installing Rust. Upgrading pip3 didn't help.

**Comment by brycedrennan** [comment] 2022-09-20 00:41
@abrambailey that's excellent info. it looks like I was mistaken about rust being installed on my system.  the tokenizer lib doesn't provide an osx arm wheel so it does have to be compiled.

**Comment by brycedrennan** [comment] 2022-09-20 00:42
I'll update the directions to include rust installation

**Comment by brycedrennan** [comment] 2022-09-20 06:21
I've updated the directions.

**Closed by brycedrennan** 2022-09-20 06:21 UTC

**Comment by brycedrennan** [comment] 2022-09-20 14:17
thanks - fixed.

**Comment by peresbri** [comment] 2023-05-30 03:12
I am getting this error on M1, 
tried installing `rust` but still not working. Anyone else had this issue?
```
Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [40 lines of output]
      The Meson build system
      Version: 1.1.1
      Source dir: /private/var/folders/ln/jyqplwh11tb1ql8rxlrp88280000gn/T/pip-install-f4urya0y/scipy_9fc0f8a3649f4b2591931528e757045b
      Build dir: /private/var/folders/ln/jyqplwh11tb1ql8rxlrp88280000gn/T/pip-install-f4urya0y/scipy_9fc0f8a3649f4b2591931528e757045b/.mesonpy-3hg2rx_m/build
      Build type: native build
      Project name: SciPy
      Project version: 1.10.1
      C compiler for the host machine: cc (clang 13.0.0 "Apple clang version 13.0.0 (clang-1300.0.29.30)")
      C linker for the host machine: cc ld64 711
      C++ compiler for the host machine: c++ (clang 13.0.0 "Apple clang version 13.0.0 (clang-1300.0.29.30)")
      C++ linker for the host machine: c++ ld64 711
      Cython compiler for the host machine: cython (cython 0.29.35)
      Host machine cpu family: aarch64
      Host machine cpu: aarch64
      Compiler for C supports arguments -Wno-unused-but-set-variable: NO
      Compiler for C supports arguments -Wno-unused-function: YES
      Compiler for C supports arguments -Wno-conversion: YES
      Compiler for C supports arguments -Wno-misleading-indentation: YES
      Compiler for C supports arguments -Wno-incompatible-pointer-types: YES
      Library m found: YES
      
      ../../meson.build:63:0: ERROR: Unknown compiler(s): [['gfortran'], ['flang'], ['nvfortran'], ['pgfortran'], ['ifort'], ['ifx'], ['g95']]
      The following exception(s) were encountered:
      Running `gfortran --version` gave "[Errno 2] No such file or directory: 'gfortran'"
      Running `gfortran -V` gave "[Errno 2] No such file or directory: 'gfortran'"
      Running `flang --version` gave "[Errno 2] No such file or directory: 'flang'"
      Running `flang -V` gave "[Errno 2] No such file or directory: 'flang'"
      Running `nvfortran --version` gave "[Errno 2] No such file or directory: 'nvfortran'"
      Running `nvfortran -V` gave "[Errno 2] No such file or directory: 'nvfortran'"
      Running `pgfortran --version` gave "[Errno 2] No such file or directory: 'pgfortran'"
      Running `pgfortran -V` gave "[Errno 2] No such file or directory: 'pgfortran'"
      Running `ifort --version` gave "[Errno 2] No such file or directory: 'ifort'"
      Running `ifort -V` gave "[Errno 2] No such file or directory: 'ifort'"
      Running `ifx --version` gave "[Errno 2] No such file or directory: 'ifx'"
      Running `ifx -V` gave "[Errno 2] No such file or directory: 'ifx'"
      Running `g95 --version` gave "[Errno 2] No such file or directory: 'g95'"
      Running `g95 -V` gave "[Errno 2] No such file or directory: 'g95'"
      
      A full log can be found at /private/var/folders/ln/jyqplwh11tb1ql8rxlrp88280000gn/T/pip-install-f4urya0y/scipy_9fc0f8a3649f4b2591931528e757045b/.mesonpy-3hg2rx_m/build/meson-logs/meson-log.txt
      + meson setup --prefix=/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11 /private/var/folders/ln/jyqplwh11tb1ql8rxlrp88280000gn/T/pip-install-f4urya0y/scipy_9fc0f8a3649f4b2591931528e757045b /private/var/folders/ln/jyqplwh11tb1ql8rxlrp88280000gn/T/pip-install-f4urya0y/scipy_9fc0f8a3649f4b2591931528e757045b/.mesonpy-3hg2rx_m/build --native-file=/private/var/folders/ln/jyqplwh11tb1ql8rxlrp88280000gn/T/pip-install-f4urya0y/scipy_9fc0f8a3649f4b2591931528e757045b/.mesonpy-native-file.ini -Ddebug=false -Doptimization=2
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed


```
