### ISSUE TITLE
Lack of Documentation on ControlNet in the Latest ImaginAIry Library Update

### ISSUE THREAD

**Issue by ripa001** [brycedrennan/imaginAIry#354] opened 2023-07-12 11:18 UTC
With recent update of the ImaginAIry, is not clear how to use ControlNet, as there were a change of parameters on the input
In version 11.0.0 I could send input as the following:
```
imagine_prompt = ImaginePrompt(
		prompt,
		control_image=image,
		control_mode=kind,
		caption_text=kind,
		steps=steps,
		seed=SEED
	)
```
Now it gives error, since control_image is not a parameter

**Comment by brycedrennan** [comment] 2024-01-03 14:19
Being worked on. Closing as duplicate of #208

**Closed by brycedrennan** 2024-01-03 14:19 UTC
Labels: documentation, planned

**Comment by brycedrennan** [comment] 2024-01-03 14:22
But yes it uses ControlInput now
```python
   caption = ""
    control_inputs = [
        ControlInput(mode="colorize", image=img, strength=2),
    ]
    prompt_add = ". color photo, sharp-focus, highly detailed, intricate, Canon 5D"
    prompt = ImaginePrompt(
        prompt=f"{caption}{prompt_add}",
        init_image=img,
        init_image_strength=0.0,
        control_inputs=control_inputs,
        size=512,
        steps=30,
        prompt_strength=12,
    )
```
